# Generated by Django 3.2.23 on 2025-12-11 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20251120_1631'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Collection',
        ),
    ]
