# Generated by Django 3.2.23 on 2025-11-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPostPayload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField(help_text='Original content of the article')),
                ('excerpt', models.TextField(blank=True, help_text='Short excerpt of the content', null=True)),
                ('slug', models.SlugField(blank=True, max_length=500, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('scheduled', 'Scheduled'), ('published', 'Published'), ('failed', 'Failed to Publish')], default='scheduled', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, help_text='When this post was published', null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='When to publish this post', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, help_text='SEO title', max_length=500, null=True)),
                ('meta_description', models.TextField(blank=True, help_text='SEO description', null=True)),
                ('meta_keywords', models.TextField(blank=True, help_text='SEO keywords', null=True)),
                ('meta_image', models.URLField(blank=True, help_text='URL of the featured image', null=True)),
                ('focus_keyword', models.CharField(blank=True, max_length=255, null=True)),
                ('og_title', models.CharField(blank=True, help_text='Open Graph title', max_length=500, null=True)),
                ('og_description', models.TextField(blank=True, help_text='Open Graph description', null=True)),
                ('og_type', models.CharField(default='article', help_text='Open Graph type', max_length=50)),
                ('twitter_card', models.CharField(default='summary_large_image', help_text='Twitter card type', max_length=50)),
                ('twitter_title', models.CharField(blank=True, help_text='Twitter card title', max_length=500, null=True)),
                ('twitter_description', models.TextField(blank=True, help_text='Twitter card description', null=True)),
                ('language', models.CharField(default='en', help_text='Content language code', max_length=10)),
                ('word_count', models.PositiveIntegerField(default=0, help_text='Number of words in the content')),
                ('reading_time', models.PositiveIntegerField(default=0, help_text='Estimated reading time in minutes')),
                ('featured', models.BooleanField(default=False, help_text='Whether this is a featured post')),
                ('canonical_url', models.URLField(blank=True, help_text='Canonical URL of the post', null=True)),
                ('last_error', models.TextField(blank=True, help_text='Last error message if publishing failed', null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
