# Generated by Django 3.2.23 on 2025-11-20 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('keyword_content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercollection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blogpostpayload',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='blogpostpayload',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='blog_posts', to='keyword_content.Category'),
        ),
        migrations.AlterUniqueTogether(
            name='usercollection',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='blogpostpayload',
            index=models.Index(fields=['status', 'scheduled_at'], name='keyword_con_status_8ad540_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpostpayload',
            index=models.Index(fields=['author'], name='keyword_con_author__e81bb2_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpostpayload',
            index=models.Index(fields=['featured'], name='keyword_con_feature_19f25f_idx'),
        ),
    ]
