# Generated by Django 3.2.23 on 2025-11-20 20:01

from django.db import migrations, models
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_content', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=255)),
                ('language', models.CharField(default='en', max_length=10)),
                ('country', models.CharField(default='us', max_length=10)),
                ('available_categories', jsonfield.fields.JSONField(default=list)),
                ('tasks', jsonfield.fields.JSONField(default=dict)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('error', 'Error')], default='processing', max_length=20)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
