# Generated by Django 3.2.23 on 2025-12-11 20:05

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('keyword_content', '0003_blogplan'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usercollection',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='usercollection',
            name='user',
        ),
        migrations.RemoveField(
            model_name='blogpostpayload',
            name='categories',
        ),
        migrations.AddField(
            model_name='blogpostpayload',
            name='categories',
            field=jsonfield.fields.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='UserCollection',
        ),
    ]
