# Generated by Django 3.2.23 on 2025-12-11 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_profile'),
        ('keyword_content', '0004_auto_20251211_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostpayload',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='user.profile'),
        ),
    ]
