# Generated by Django 3.2.23 on 2025-11-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(max_length=1000, unique=True)),
                ('source', models.CharField(db_index=True, max_length=100)),
                ('source_type', models.CharField(choices=[('google', 'Google News'), ('yahoo', 'Yahoo News'), ('other', 'Other')], db_index=True, max_length=10)),
                ('category', models.CharField(db_index=True, max_length=100)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('error', 'Error')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(default='en', max_length=10)),
                ('country', models.CharField(default='us', max_length=10)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
