# Generated by Django 3.2.23 on 2025-11-20 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('scraper', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapedarticle',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scraped_articles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='scrapedarticle',
            index=models.Index(fields=['source_type', 'category'], name='scraper_scr_source__648502_idx'),
        ),
        migrations.AddIndex(
            model_name='scrapedarticle',
            index=models.Index(fields=['status', 'published_at'], name='scraper_scr_status_0fea05_idx'),
        ),
    ]
