# Generated by Django 3.2.23 on 2025-12-11 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScrapedArticle',
        ),
    ]
