# Generated by Django 3.2.23 on 2025-11-20 16:08

from django.db import migrations, models
import keyword_content.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField(help_text='Content of the article')),
                ('excerpt', models.TextField(blank=True, help_text='Short excerpt of the content', null=True)),
                ('slug', models.SlugField(blank=True, max_length=500, unique=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('published', 'Published'), ('pending', 'Pending Review'), ('failed', 'Failed to Publish'), ('archived', 'Archived')], default='scheduled', max_length=20)),
                ('publishedAt', models.DateTimeField(blank=True, help_text='When this post was published', null=True)),
                ('scheduledAt', models.DateTimeField(blank=True, help_text='When to publish this post', null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('categoryIds', keyword_content.fields.ListField(default=list, help_text='List of category ObjectId strings')),
                ('tagIds', keyword_content.fields.ListField(default=list, help_text='List of tag ObjectId strings')),
                ('tags', keyword_content.fields.ListField(default=list, help_text='List of tags')),
                ('authorId', models.CharField(blank=True, max_length=255, null=True)),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('metaTitle', models.CharField(blank=True, help_text='SEO title', max_length=500, null=True)),
                ('metaDescription', models.TextField(blank=True, help_text='SEO description', null=True)),
                ('metaKeywords', models.TextField(blank=True, help_text='SEO keywords', null=True)),
                ('metaImage', models.URLField(blank=True, help_text='URL of the featured image', null=True)),
                ('ogTitle', models.CharField(blank=True, help_text='Open Graph title', max_length=500, null=True)),
                ('ogDescription', models.TextField(blank=True, help_text='Open Graph description', null=True)),
                ('ogType', models.CharField(default='article', help_text='Open Graph type', max_length=50)),
                ('twitterCard', models.CharField(default='summary_large_image', help_text='Twitter card type', max_length=50)),
                ('twitterDescription', models.TextField(blank=True, help_text='Twitter card description', null=True)),
                ('focusKeyword', models.CharField(blank=True, help_text='Primary keyword for the post', max_length=255, null=True)),
                ('language', models.CharField(default='en', help_text='Content language code', max_length=50)),
                ('word_count', models.IntegerField(default=0, help_text='Number of words in the content')),
                ('readingTime', models.IntegerField(default=0, help_text='Estimated reading time in minutes')),
                ('target_path', models.CharField(blank=True, help_text='Target database and collection in format: db.collection (e.g., CRM.posts)', max_length=500, null=True)),
                ('canonicalUrl', models.URLField(blank=True, help_text='Canonical URL of the post', null=True)),
                ('featured', models.BooleanField(default=False, help_text='Whether this is a featured post')),
                ('content_type', models.CharField(blank=True, max_length=100, null=True)),
                ('image_urls', keyword_content.fields.ListField(default=list, help_text='List of image URLs')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional metadata in JSON format')),
                ('lastError', models.TextField(blank=True, help_text='Last error message if publishing failed', null=True)),
            ],
            options={
                'verbose_name': 'News Post',
                'verbose_name_plural': 'News Posts',
                'db_table': 'content',
                'ordering': ['-scheduledAt', '-createdAt'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('domain', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_scraped', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
