# Generated by Django 3.2.23 on 2025-12-11 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_content', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsCategory',
        ),
        migrations.DeleteModel(
            name='NewsSource',
        ),
        migrations.DeleteModel(
            name='NewsPost',
        ),
    ]
