# Generated by Django 3.2.23 on 2025-12-11 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PublishedPost',
        ),
        migrations.DeleteModel(
            name='ScheduledPost',
        ),
    ]
