# Generated by Django 3.2.23 on 2025-12-22 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0004_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0002_auto_20251211_2005'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('keyword', models.CharField(max_length=255)),
                ('language', models.CharField(default='en', max_length=10)),
                ('country', models.CharField(default='us', max_length=10)),
                ('available_categories', jsonfield.fields.JSONField(default=list)),
                ('tasks', jsonfield.fields.JSONField(default=dict)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('error', 'Error')], default='processing', max_length=20)),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlogPostPayload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Post title', max_length=500)),
                ('content', models.TextField(help_text='HTML content of the article')),
                ('excerpt', models.TextField(blank=True, help_text='Short excerpt of the content', null=True)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly slug', max_length=500, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Review'), ('scheduled', 'Scheduled'), ('publishing', 'Publishing'), ('published', 'Published'), ('failed', 'Failed to Publish')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, help_text='When this post was published', null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='When to publish this post', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', jsonfield.fields.JSONField(blank=True, default=list, help_text='Array of category IDs')),
                ('meta_title', models.CharField(blank=True, help_text='SEO title', max_length=500, null=True)),
                ('meta_description', models.TextField(blank=True, help_text='SEO description', null=True)),
                ('meta_keywords', models.TextField(blank=True, help_text='SEO keywords', null=True)),
                ('meta_image', models.URLField(blank=True, help_text='URL of the featured image', null=True)),
                ('focus_keyword', models.CharField(blank=True, help_text='Primary SEO keyword', max_length=255, null=True)),
                ('og_title', models.CharField(blank=True, help_text='Open Graph title', max_length=500, null=True)),
                ('og_description', models.TextField(blank=True, help_text='Open Graph description', null=True)),
                ('og_type', models.CharField(default='article', help_text='Open Graph type', max_length=50)),
                ('twitter_card', models.CharField(default='summary_large_image', help_text='Twitter card type', max_length=50)),
                ('twitter_title', models.CharField(blank=True, help_text='Twitter card title', max_length=500, null=True)),
                ('twitter_description', models.TextField(blank=True, help_text='Twitter card description', null=True)),
                ('language', models.CharField(default='en', help_text="Content language code (e.g., 'en', 'fr')", max_length=10)),
                ('word_count', models.PositiveIntegerField(default=0, help_text='Number of words in the content')),
                ('reading_time', models.PositiveIntegerField(default=0, help_text='Estimated reading time in minutes')),
                ('featured', models.BooleanField(default=False, help_text='Whether this is a featured post')),
                ('canonical_url', models.URLField(blank=True, help_text='Canonical URL / WordPress site URL', null=True)),
                ('last_error', models.TextField(blank=True, help_text='Last error message if publishing failed', null=True)),
                ('source_url', models.URLField(blank=True, help_text='Original source URL (for news posts)', null=True)),
                ('source_name', models.CharField(blank=True, help_text='Original source name', max_length=255, null=True)),
                ('author', models.ForeignKey(blank=True, help_text='Post author', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_posts', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(blank=True, help_text='User profile associated with this post', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='user.profile')),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='blogpostpayload',
            index=models.Index(fields=['status', 'scheduled_at'], name='content_status_scheduled_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpostpayload',
            index=models.Index(fields=['author'], name='content_author_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpostpayload',
            index=models.Index(fields=['featured'], name='content_featured_idx'),
        ),
        migrations.AddIndex(
            model_name='blogpostpayload',
            index=models.Index(fields=['created_at'], name='content_created_idx'),
        ),
    ]
