# Generated by Django 3.2.23 on 2025-12-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostpayload',
            name='og_image',
            field=models.URLField(blank=True, help_text='Open Graph image URL', null=True),
        ),
        migrations.AddField(
            model_name='blogpostpayload',
            name='twitter_image',
            field=models.URLField(blank=True, help_text='Twitter card image URL', null=True),
        ),
    ]
